VoodooTeam/airbyte

airbyte-integrations/connectors/source-facebook-marketing/integration_tests/configured_catalog.json
airbyte-integrations/connectors/source-facebook-marketing/integration_tests/configured_catalog_short.json
airbyte-integrations/connectors/source-facebook-marketing/main.py
airbyte-integrations/connectors/source-facebook-marketing/sample_files/sample_config.json
airbyte-integrations/connectors/source-facebook-marketing/setup.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/common.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/patches.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py

Optimize facebook connector using gevent parallelism

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py

fix: set checkpoint interval

---

airbyte-integrations/connectors/source-facebook-marketing/integration_tests/configured_catalog.json
airbyte-integrations/connectors/source-facebook-marketing/integration_tests/configured_catalog_short.json
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_rule_libraries.json
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py

feat: add support for ad rule libraries

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py

Hashed token is not a string

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Fix rate limit problem in applovin

---

airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/schemas/ad_groups.json
airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/schemas/ads.json
airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/schemas/campaigns.json

This reverts commit cb23c116f1d5668d6d8d70b3c050099b9c3bc1c5.
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rC …

Revert "Add primary_status fields to ad_groups, ads, and campaigns"

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py

Fix insights multi-account slicing

---

airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Google ads: ignore deactivated accounts, while leaving logs in

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_sets.json

Source Facebook Marketing - Add adset optimization goal

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/campaigns.json

Source Facebook Marketing - Add campaigns is_skadnetwork_attribution

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/common.py
airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/campaign_criterion.json
airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Source Google Ads - evolutions

---

airbyte-integrations/connectors/source-facebook-marketing/Dockerfile
airbyte-integrations/connectors/source-google-ads/Dockerfile
airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile

Rollback dockerfile removal

---

airbyte-integrations/connectors/source-facebook-marketing/integration_tests/ads_insights_configured_catalog_bis.json
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/utils.py

Add proper handling of optional end date in config

fix: handle missing end date

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py

fix: remove owner field from account stream

---

airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Google adds was deduplicated too much rows because of a bug

---

airbyte-integrations/connectors/source-google-ads/integration_tests/configured_catalog_voodoo.json
airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Modify primary key of campaign budget to campaign.id

---

airbyte-integrations/connectors/source-ironsource/source_ironsource/streams.py

Source Ironsource - fix authenticator renewal

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/schemas/offers.json

Mintegral schema fix

---

airbyte-integrations/connectors/source-ironsource/source_ironsource/schemas/campaign_targetings.json
airbyte-integrations/connectors/source-ironsource/source_ironsource/schemas/campaigns.json
airbyte-integrations/connectors/source-ironsource/source_ironsource/schemas/country_groups.json
airbyte-integrations/connectors/source-ironsource/source_ironsource/streams.py

This PR fixes a bug where campaigns would get duplicated, and adds some fields which were missing and mistyped.

Source Ironsource: fix campaign duplicates and missing fields

---

airbyte-integrations/connectors/source-ironsource/source_ironsource/schemas/campaign_creatives.json
airbyte-integrations/connectors/source-ironsource/source_ironsource/streams.py

This PR fixes more anomalies on campaign related tables

Source Ironsource: fix missing campaignids

---

airbyte-integrations/connectors/source-mintegral/integration_tests/configured_catalog.json
airbyte-integrations/connectors/source-mintegral/source_mintegral/schemas/campaigns.json
airbyte-integrations/connectors/source-mintegral/source_mintegral/source.py
airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral campaigns stream

---

airbyte-integrations/connectors/source-ironsource/source_ironsource/schemas/campaign_targetings.json

Source Ironsource: adapt to API changes

---

airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Source Googleads: fix backfill cursor timestamp parsing

---

airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

Fix: discard metrics import for manager accounts

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py

Source Facebook Marketing: Add default thottling config

---

airbyte-integrations/connectors/source-applovin/source_applovin/schemas/publisher_reports.json
airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: adds pagination to the strams

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: ignore zero metrics

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: increase page size for reporting

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: try new page size

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

… This will allow us to profile how much time is lost on writing.
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDD …

Applovin: Deploy a test where we only keep the first metric per page.This will allow us to profile how much time is lost on writing.

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: remove checkpoint for metrics

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin metrics: more entities per page

---

airbyte-integrations/connectors/source-snapchat-marketing/.dockerignore
airbyte-integrations/connectors/source-snapchat-marketing/Dockerfile

Fixes missing dockerfiles for snapchat and tiktok

fix: missing dockerfiles and switch to poetry build

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py

fix: remove checkpointing

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/async_job.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/common.py

Source Facebook Marketing: retry on connectivity issues

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/__init__.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py

Source Facebook Marketing: Re-enable checkpointing

---

airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/streams.py

Tested locally, but it looks like staging behaviour differs

Tiktok: debug start date taken from state

---

airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/streams.py

Source Tiktok Marketing: reset 40002 counter on success

---

.circleci/config.yml
airbyte-integrations/connectors/destination-postgres/Dockerfile

Postgres: initial circle ci deployment for postgres destination

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral: state was saved in a format that was parsed incorrectly

---

airbyte-integrations/connectors/destination-postgres/Dockerfile

Postgres: upgrade docker image

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/schemas/reports.json
airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral staging: use different utc for insights

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/schemas/reports.json
airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral: schema modifications for reporting

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/schemas/reports.json
airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral: schema modifications for reporting lowercase + underscore

---

airbyte-integrations/connectors/source-mintegral/source_mintegral/streams.py

Mintegral: reporting type param for API wasn't handled as expected

---

airbyte-integrations/connectors/source-applovin/source_applovin/streams.py

Applovin: metrics should have numeric values instead of strings

---

airbyte-integrations/connectors/source-applovin/setup.py

Applovin: hardcore airbyte-cdk version
